apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-01
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx
---

apiVersion: v1
kind: Pod
metadata:
  name: rs-01-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/nginx

