apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-01
  labels:
    app: nginx
  annotations:
    controller.kubernetes.io/pod-deletion-cost: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.20
---

apiVersion: v1
kind: Pod
metadata:
  name: rs-01-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/nginx

## Always maintain unique labels.
