apiVersion: v1
kind: Pod
metadata:
  name: pod-07
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
      - name: CATALOGUE_HOST
        value: "hello from catalogue"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-07
data:
  CATALOGUE_HOST: "catalogue"
  CART_HOST: "cart"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-07-cm
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
      - name: CATALOGUE_HOST
        valueFrom:
          configMapKeyRef:
            name: cm-07
            key: CATALOGUE_HOST
      - name: CART_HOST
        valueFrom:
          configMapKeyRef:
            name: cm-07
            key: CART_HOST

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-07-cm-1
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      envFrom:
      - configMapRef:
          name: cm-07

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-07-file
data:
  catalogue.service: |
    [Unit]
    Description = Catalogue Service

    [Service]
    User=roboshop
    Environment=MONGO={{ secrets.MONGO }}
    Environment=MONGO_URL="{{ secrets.MONGO_URL }}"
    ExecStart=/bin/node /app/server.js
    SyslogIdentifier=catalogue

    [Install]
    WantedBy=multi-user.target

  cart.service: |
    [Unit]
    Description = Cart Service

    [Service]
    User=roboshop
    Environment=MONGO={{ secrets.MONGO }}
    Environment=MONGO_URL="{{ secrets.MONGO_URL }}"
    ExecStart=/bin/node /app/server.js
    SyslogIdentifier=cart

    [Install]
    WantedBy=multi-user.target

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-07-cm-2
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: cm-07-file

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-07-1
data:
  password: YWJjZEAxMjM0

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-07-secret
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
      - name: password
        valueFrom:
          secretKeyRef:
            name: secret-07-1
            key: password
