---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    appName: nginx
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    appName: debug
spec:
  containers:
    - name: debug
      image: rkalluru/debug
---
# apiVersion: security.istio.io/v1
# kind: AuthorizationPolicy
# metadata:
#  name: allow-nothing
# spec:
#   {}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-debug
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["default"]
    - source:
        namespaces: ["test"]
  - to:
    - operation:
        paths: ["/"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: test
  labels:
    appName: debug
spec:
  containers:
    - name: debug
      image: rkalluru/debug
