apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    appName: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: roboshop
  labels:
    appName: frontend
spec:
  containers:
    - name: frontend
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    env:
    - name: CATALOGUE_HOST
      value: "Hello from the environment"
    - name: CATALOGUE_PORT
      value: "Such a sweet sorrow"
    - name: USER_HOST
      value: "Such a sweet sorrow"
    - name: USER_PORT
      value: "Such a sweet sorrow"
    - name: CART_HOST
      value: "Such a sweet sorrow"
    - name: CART_PORT
      value: "Such a sweet sorrow"
    - name: SHIPPING_HOST
      value: "Such a sweet sorrow"
    - name: SHIPPING_PORT
      value: "Such a sweet sorrow"
    - name: PAYMENT_HOST
      value: "Such a sweet sorrow"
    - name: PAYMENT_PORT
      value: "Such a sweet sorrow"

