apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    appName: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  namespace: roboshop
  labels:
    appName: payment
spec:
  containers:
    - name: payment
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
      env:
        - name: CART_HOST
          value: "cart"
        - name: CART_PORT
          value: "8080"
        - name: USER_HOST
          value: "user"
        - name: USER_PORT
          value: "8080"
        - name: AMQP_HOST
          value: 'rabbitmq.dev.rdevopsb80.online'
        - name: AMQP_USER
          value: 'roboshop'
        - name: AMQP_PASS
          value: 'roboshop123'

